FROM apache/airflow:2.10.5

USER root

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

RUN python -m pip install --no-cache-dir --force-reinstall \
    "dbt-core==1.8.7" \
    "dbt-postgres==1.8.2"